spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagelite
    username: postgres
    password: postgres

  jpa:
    databse: POSTGRESQL
    hibernate:
      dat-auto: update
    show-sqt: true
